# Generated by Django 2.0.6 on 2018-06-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20180617_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
