# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-24 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleManage', '0002_auto_20161209_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterField(
            model_name='articlecolumn',
            name='column',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 24, 13, 15, 20, 110261, tzinfo=utc)),
        ),
    ]
