# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-09 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleManage', '0004_auto_20170103_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 9, 13, 27, 56, 512551, tzinfo=utc)),
        ),
    ]
