# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 02:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleManage', '0005_auto_20170109_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 2, 19, 51, 926905, tzinfo=utc)),
        ),
    ]
