# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-13 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleManage', '0007_auto_20170113_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='article_tag',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='ArticleManage.ArticleTag'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 13, 11, 24, 31, 221664, tzinfo=utc)),
        ),
    ]
