# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleManage', '0009_auto_20170124_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 1, 16, 9, 55, 357663, tzinfo=utc)),
        ),
    ]
