# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-19 06:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleManage', '0010_auto_20170202_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 19, 6, 46, 19, 477219, tzinfo=utc)),
        ),
    ]
