# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 09:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleManage', '0011_auto_20170219_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 9, 46, 28, 405904, tzinfo=utc)),
        ),
    ]
