# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-11 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleManage', '0012_auto_20170309_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 9, 48, 53, 890037, tzinfo=utc)),
        ),
    ]
