# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentator',
            field=models.CharField(max_length=90),
        ),
    ]
