# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 01:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20170430_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 1, 1, 31, 18, 879434, tzinfo=utc)),
        ),
    ]
