# Generated by Django 2.0.6 on 2018-06-13 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180613_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 10, 27, 29, 854156, tzinfo=utc)),
        ),
    ]
