# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 10:11
from __future__ import unicode_literals

import course.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lesson_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=course.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
