# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-16 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_delete_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='lesson',
        ),
    ]
