# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-28 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_lesson_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
