# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-28 06:59
from __future__ import unicode_literals

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20170328_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='attach',
            field=models.FileField(blank=True, upload_to=course.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to=course.models.user_directory_path),
        ),
    ]
