# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogArticles',
        ),
    ]
