# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-created',)},
        ),
    ]
