# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='aboutme',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=177),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.CharField(blank=True, max_length=97),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(blank=True, max_length=27),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='school',
            field=models.CharField(blank=True, max_length=97),
        ),
    ]
